name: cabibook
description: "A cab booking app built with Flutter"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  country_picker: ^2.0.27
  very_good_analysis: ^9.0.0
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.3  # ✅ Move the version here!

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300

# ✅ Now put the splash config **after everything**, like this:
flutter_native_splash:
  color: "#BE045E"
  image: assets/image/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center